#!/bin/sh

. /etc/rc.subr

name="sctd"

rcvar="${name}_enable"
# Enable the service by default.
eval ${rcvar}="yes"

required_dir="$HOME/.cache"
procname="$name"
pidfile="$HOME/.cache/$name.pid"

# This hack makes it possible to run rc(8) services as a non-root user.
limits() {
	shift 2
	"$@"
}

command="/usr/sbin/daemon"
command_args="-o $HOME/.cache/$name.log -p $pidfile -- $procname --latitude 52.520008 --longitude 13.404954"

extra_commands="log"
log_cmd="${PAGER:-cat} $HOME/.cache/$name.log"

run_rc_command "$1"
