#! /bin/sh -

. ../lib.sh

set -eu

FILES=""
goat="$HOME/.local/bin/goat"

lib_info setup

cd goat
./setup --destination "${goat%/*}"

while [ $# -gt 0 ]
do
    case "$1" in
        --defaults)
            shift
            set +e
            export GOAT_PATH="$HOME/.goat"
            $goat link bin ~/.local/bin
            $goat link desk ~/Desktop
            $goat link docs ~/Documents
            $goat link dots ~/.dotfiles
            $goat link down ~/Downloads
            $goat link drop ~/Dropbox
            $goat link h ~/h
            set -e
            ;;
        *)
            break
            ;;
    esac
done

lib_info 'setup done'
