#! /bin/sh -
#
# Options:
#     --name
#     --email

. ../lib.sh

set -eu

MODULE_NAME=git
GITCONFIG='gitconfig'
FILES="$GITCONFIG"

GITCONFIG_LOCAL="$GITCONFIG.local"

lib_install() {
    lib_install_file "$PWD/$GITCONFIG_LOCAL" "$HOME/.$GITCONFIG"
}

lib_info 'setup'

lib_back_up
trap lib_roll_back EXIT

git_name=
git_email=
while [ $# -gt 0 ]
do
    case "$1" in
        --name)
            shift 1
            if [ $# -eq 0 ]
            then
                lib_err "name not provided for the --name option"
                exit 1
            fi
            git_name="$1"
            shift 1
            ;;

        --email)
            shift 1
            if [ $# -eq 0 ]
            then
                lib_err "email not provided for the --email option"
                exit 1
            fi
            git_email="$1"
            shift 1
            ;;

        *)
            shift
            break
            ;;
    esac
done

touch "$PWD/$GITCONFIG_LOCAL"
if [ -z "$git_name" ]
then
    printf 'Name: '
    read git_name
fi
if [ -z "$git_email" ]
then
    printf 'Email: '
    read git_email
fi

cat <<EOF >> "$PWD/$GITCONFIG_LOCAL"
[user]
    name = $git_name
    email = $git_email

[include]
    path = $PWD/gitconfig

EOF

lib_install
trap - EXIT

lib_info 'setup done'
