#! /bin/sh -

set -eu

MODULE_NAME=git
FILES='gitconfig'
GITCONFIG_LOCAL='gitconfig.local'

info() {
    echo $MODULE_NAME: $*
}

roll_back() {
    set +e
    info roll back due to an error
    for file in $FILES
    do
        cp -i -a -v -- "$BACKUP_DIR/.$file" "$HOME/.$file"
    done
}

info setup

# Back up.
for file in $FILES
do
    if [ -e "$HOME/$file" ]
    then
        cp -i -a -v -- "$HOME/.$file" "$BACKUP_DIR/.$file"
    fi
done

# Preprocessing.
touch "./$GITCONFIG_LOCAL"
printf 'Name: '
read git_username
printf 'Email: '
read git_email
cat <<EOF >> "./$GITCONFIG_LOCAL"
[user]
    name = $git_username
    email = $git_email

[include]
    path = $PWD/gitconfig

EOF

# Link.
trap roll_back EXIT
ln -s -v -f -F -n -- "$PWD/gitconfig.local" "$HOME/.gitconfig"
trap - EXIT

info setup done
