.\"
.\" SPDX-License-Identifier: BSD-2-Clause-FreeBSD
.\"
.\" Copyright (c) 2018 Mateusz Piotrowski <0mp@FreeBSD.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd July 6, 2018
.Dt DOTFILES 8
.Os
.Sh NAME
.Nm dotfiles
.Nd "various configuration scripts, dotfiles and utilities"
.Sh SYNOPSIS
.Cm ./setup
.Op Ar module Oo Oo Ar option ... Oc Cm -- Oc Ar ...
.Sh DESCRIPTION
.Nm
is a framework to manage configuration scripts, dotfiles and utilities.
.Pp
The modules are as follows:
.Bl -tag -width ".Cm freebsd-desktop" -compact
.It Cm bash
Install Bash
configuration files.
.It Cm firefox
Configure Firefox with
.Pa user.js .
.It Cm freebsd-current
Configure a
.Fx
machine running CURRENT.
This module sets some development-specific variables in
.Xr make.conf 5 ,
.Xr src.conf 5 ,
and
.Xr src-env.conf 5 .
.It Cm freebsd-desktop Op Ar option ...
Configuration files for a
.Fx
desktop.
.Bl -tag -width ".Fl -powerdxx"
.It Fl -fonts
Install and configure additional fonts.
.It Fl -powerdxx
Install powerd++ for a better power management than the one offered by
.Xr powerd 8 .
.El
.It Cm freebsd-dwm Op Ar option ...
Configuration of a desktop environment running the dwm window manager.
The options are as follows:
.Bl -tag -width ".Fl -wallpaper"
.It Fl -install
Recompile and reinstall dwm.
.It Fl -wallpaper
Set up a wallpaper using feh.
This option succeeds only when Xorg is running.
.El
.It Cm freebsd-general
Install some
.Fx
general purpose utilities and configuration files.
.It Cm freebsd-haseeq540s
Configure
.Fx
desktop experience for Hasee Q540S.
.It Cm freebsd-l702x Op Ar option ...
Configure
.Fx
desktop experience for Dell XPS L702X.
The options are as follows:
.Bl -tag -width ".Fl -nvidia"
.It Fl -nvidia
Install an Nvidia graphics driver.
.El
.It Cm freebsd-st
Recompile and reinstall st terminals.
.It Cm freebsd-yoga314 Op Ar option ...
Configure
.Fx
desktop experience for Lenovo Yoga 3 14.
The options are as follows:
.Bl -tag -width ".Fl -powerdxx"
.It Fl -intel
Install Intel graphics kernel modules.
.El
.It Cm git Op Ar option ...
Configure Git.
The options are as follows:
.Bl -tag -width ".Fl -email Ar email"
.It Fl -email Ar email
The email to set in
.Pa ~/.gitconfig .
Defaults to
.Sq 0mp@FreeBSD.org .
.It Fl -github-ssh
Configure Git to replace
.Dq Li "https://github.com/"
with
.Dq Li "ssh://git@github.com/"
so that SSH is used even if a repository is configured to use HTTPS.
.It Fl -name Ar name
The name to set in
.Pa ~/.gitconfig .
Defaults to
.Sq Mateusz Piotrowski .
.El
.It Cm gnupg
Install GnuPG configuration files.
.It Cm goat Op Fl -defaults
Install goat.
Using
.Fl -defaults
populates goat with some default shortcuts.
.It Cm macos Op Ar option ...
Configure macOS.
The options are as follows:
.Bl -tag -width ".Fl -bash"
.It Fl -bash
Install Bash 4 with Homebrew.
.El
.It Cm octave
Instal octave-cli configuration files.
.It Cm subversion
Install Subversion configuration files.
.It Cm tmux
Install tmux configuration files.
.It Cm utils
Install general purpose utilities.
.It Cm vim
Configure Vim and install related configuration files.
.It Cm x11
Install Xorg-related configuration files.
.It Cm xpdf
Install Xpdf configuration files.
.El
.Sh EXAMPLES
Install
.Cm bash
and
.Cm git
modules:
.Bd -literal -offset indent
\&./setup bash git --name 'Charlie Root' --email 'root@example.org' --
.Ed
.Sh AUTHORS
.An Mateusz Piotrowski Aq Mt 0mp@FreeBSD.org
