#! /bin/sh -
#
# NB: In Vim, execute selection with ":terminal sh".

clean_up() {
	if [ "$SSH_AGENT_PID" ]; then
		kill "$SSH_AGENT_PID"
	fi

	for s in ~/.local/etc/rc.d/*; do
		$s stop
	done
}

trap 'clean_up' EXIT

export LANG=en_US.UTF-8
export LC_TIME=en_GB.UTF-8

# This is a workaround for dwm not being able to handle Java-based GUI
# applications properly. This is an OpenJDK-specific options. See the dwm(1)
# manual page for more details.
export _JAVA_AWT_WM_NONREPARENTING=1

mkdir -p ~/.cache
for s in ~/.local/etc/rc.d/*; do
	$s start
done

[ -f ~/.xmodmap ] && xmodmap ~/.xmodmap

eval $(ssh-agent -s)
gpg-connect-agent reloadagent /bye

xrdb -merge ~/.Xresources

$(which dbus-run-session) sh -c '
	"$@"
	while [ -f ~/.cache/restart-dwm ]; do
		"$@" || break
	done
' xinitsh "${@:-dwm}"
