#! /bin/sh -
#
# NB: In Vim, execute selection with ":terminal sh".

clean_up() {
    if [ "$SSH_AGENT_PID" ]; then
        kill "$SSH_AGENT_PID"
    fi

    pkill -F ~/.cache/svscan.pid
}

trap 'clean_up' EXIT

export LANG=en_US.UTF-8
export LC_TIME=en_GB.UTF-8

# This is a workaround for dwm not being able to handle Java-based GUI
# applications properly. This is an OpenJDK-specific options. See the dwm(1)
# manual page for more details.
export _JAVA_AWT_WM_NONREPARENTING=1
# This is a workaround for a freezing Firefox process when sharing a screen
# during a video call while using the scfb(4) driver. I am not using the i915
# driver because as of eb8bf6bb4204 the kernel panics when a screen is shared
# (not immediately, but after a couple of minutes of intensive video workload).
export LIBGL_DRI3_DISABLE=yes

mkdir -p ~/.cache
daemon -l user -p ~/.cache/svscan.pid -T svscan -- svscan ~/.local/daemontools

[ -f ~/.xmodmap ] && xmodmap ~/.xmodmap

eval $(ssh-agent -s)
gpg-connect-agent reloadagent /bye

$(which dbus-run-session) sh -c '
	"$@"
	while [ -f ~/.cache/restart-dwm ]; do
		"$@" || break
	done
' xinitsh "${@:-dwm}"
