#! /bin/sh -

set -eu

if [ "@$(pwd -P)@" != "@$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)@" ]
then
    echo 'usage: ./setup [target [[options...] --]]...' 1>&2
    exit 1
fi

readonly BACKUP_DIR="$PWD/backup/$(date +%y-%m-%d.%H-%M-%S)"
export BACKUP_DIR

mkdir -p "$BACKUP_DIR"
if ! [ -d "$BACKUP_DIR" ]
then
    echo failed to create a backup directory 1>&2
    exit 1
fi

while [ $# -gt 0 ]
do
    (cd "$1"; export MODULE_NAME="${1%/}"; shift; ./setup "$@")
    shift
    # Remove command line arguments matching '--*' before the next module.
    if [ $# -gt 0 ] && [ @--@ = "@${1%"${1#??}"}@" ]
    then
        while [ $# -gt 0 ]
        do
            if [ @--@ = "@$1@" ]
            then
                shift
                break
            else
                shift
            fi
        done
    fi
done
