#! /bin/sh -

set -eu

if [ ! "x$PWD" = "x$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)" ]; then
    echo 'usage: ./setup target [target ...]'
    exit 1
fi

readonly BACKUP_DIR="$PWD/backup/$(date +%y-%m-%d-%H-%M-%S)"
export BACKUP_DIR

mkdir -p "$BACKUP_DIR"

while [ $# -gt 0 ]
do
    (cd "$1"; ./setup)
    shift 1
done

