---
- name: Install packages
  package: name={{item}} state=present
  become: yes
  with_items:
    - hs-xmonad
    - hs-xmonad-contrib
    - hs-xmobar

- name: Configure and start D-Bus
  become: yes
  service:
    name: dbus
    state: started
    enabled: yes
