#! /bin/sh -

. ../lib.sh

set -eu

MODULE_NAME=vim
# XXX: Keeping a directory here might not be the best idea.
FILES='vimrc vim/colors'
BUNDLE_DIR="$HOME/.vim/bundle"
VUNDLE_PLUGIN_DIR="$BUNDLE_DIR/Vundle.vim"
VUNDLE_REPO='https://github.com/VundleVim/Vundle.vim.git'

lib_info setup

lib_back_up

mkdir -p "$BUNDLE_DIR"

# Install Vundle.
if [ ! -d "$VUNDLE_PLUGIN_DIR" ]
then
    git clone "$VUNDLE_REPO" "$VUNDLE_PLUGIN_DIR"
fi

trap lib_roll_back EXIT
lib_install
trap - EXIT

# Install plugins.
vim +PluginInstall +PluginUpdate +qall

lib_info 'setup done'
