#! /bin/sh -

. ../lib.sh

set -eu

vim_dir="$HOME/.vim"

lib_info setup

# 1. Install Vundle.
vundle_dir="$vim_dir/bundle"
vundle_plugin_dir="$vundle_dir/Vundle.vim"
vundle_repo='https://github.com/VundleVim/Vundle.vim.git'
mkdir -p "$vundle_dir"
if [ ! -d "$vundle_plugin_dir" ]
then
    git clone "$vundle_repo" "$vundle_plugin_dir"
fi

# 2. Install vimrc.
FILES='vimrc'
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

# 3. Install color schemes.
FILES='monochrome.vim monokai.vim robpike.vim'
PREFIX="$vim_dir/colors/"
colors_dir="$vim_dir/colors"
lib_back_up
if [ -h "$colors_dir" ] || [ -e "$colors_dir" ] && [ ! -d "$colors_dir" ]
then
    lib_back_up_file "$colors_dir" "${colors_dir##*/}"
    rm -rf "$colors_dir"
fi
mkdir -p "$colors_dir"
trap lib_roll_back EXIT
lib_install
trap - EXIT
PREFIX=

# 4. Install Vundle plugins.
vim +PluginInstall +PluginUpdate +qall

# 5. Install templates.
FILES='Makefile'
PREFIX="/home/0mp/.vim/templates/"
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
