#! /bin/sh -

info() {
    echo $MODULE_NAME: $*
}

roll_back() {
    set +e
    info roll back due to an error
    for file in $FILES
    do
        cp -i -a -v -- "$BACKUP_DIR/.$file" "$HOME/.$file"
    done
}

set -eu

FILES='vimrc vim/colors'

info setup

# Back up.
for file in $FILES
do
    if [ -e "$HOME/$file" ]
    then
        cp -i -a -v -- "$HOME/.$file" "$BACKUP_DIR/.$file"
    fi
done

# Preprocessing.
mkdir -p "$HOME/.vim/bundle"

# Install Vundle.
set +e
git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
set -e

trap roll_back EXIT
for file in $FILES;
do
    ln -s -v -f -F -n -- "$PWD/$file" "$HOME/.$file"
done
trap - EXIT

# Install plugins.
vim +PluginInstall +PluginUpdate +qall

info setup done
