---
- name: Install Bash
  package:
    name:
      - bash
      - bash-completion
    state: present
  become: yes

- name: Change the default login shell to Bash on FreeBSD
  become: yes
  user: name={{ ansible_user }} shell="/usr/local/bin/bash"
  when: ansible_facts['os_family'] == "FreeBSD"
