#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

FILES=''
PREFIX=""
CUSTOMOPTS="$(opts="${*%--}"; printf -- '%s' "${opts%% -- *}")"
lib_custom_install() {
    case $CUSTOMOPTS in
        *--install*)
            lib_run_as_root $CUSTOMOPTS
            ;;
    esac

    if [ -w ~/.0mp-switch/profile ]
    then
        echo Shine > ~/.0mp-switch/profile
    fi
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
