#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

lib_require_root

FILES=
PREFIX=
CUSTOMFILES=
CUSTOMOPTS="$(opts="${@%--}"; printf -- "${opts%% -- *}")"
lib_custom_install() {
    # Turn on additional checks for ports.
    sysrc -f /etc/make.conf DEVELOPER=YES

    # Disable the delay after a warning. For example there will be no delay
    # after a warning about a missing LICENSE variable when building a port.
    sysrc -f /etc/make.conf DEV_WARNING_WAIT=0

    # Use ccache(1).
    sysrc -f /etc/src.conf WITH_CCACHE_BUILD=YES

    # Use meta mode. See src-env.conf(5) for details.
    sysrc -f /etc/src-env.conf WITH_META_MODE=YES
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
