#! /bin/sh -
#
# References:
# - profiles.ini:
#   http://kb.mozillazine.org/Profiles.ini_file

. ../lib.sh

set -eu

FILES="userChrome.css"

tbdir="$HOME/.thunderbird"
tbprofiles="$HOME/.thunderbird/profiles.ini"

# PREFIX - The extracted profile directory name will be assigned to this
#          variable.
extract_default_profile_path() {
    profilepath=
    isdefault=0

    while read line
    do
        case "$line" in
            '[Profile'*)
                if [ "x$isdefault" = "x1" ] && [ -n "$profilepath" ]
                then
                    break
                fi
                profilepath=
                ;;
            'Path='*)
                profilepath="${line#Path=}"
                ;;
            'Default='*)
                isdefault="${line#Default=}"
                ;;
        esac
    done < "$tbprofiles"

    if [ -n "$profilepath" ]
    then
        PREFIX="$tbdir/$profilepath/chrome/"
        return 0
    else
        lib_err "failed to extract the default profile path from $tbprofiles"
        return 1
    fi
}

lib_info 'setup'

if [ ! -d "$tbdir" ]
then
    lib_err "$tbdir is missing"
    exit 1
elif [ ! -f "$tbprofiles" ]
then
    lib_err "$tbprofiles is missing"
    exit 1
fi

extract_default_profile_path

lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
