.\"
.\" SPDX-License-Identifier: BSD-2-Clause-FreeBSD
.\"
.\" Copyright (c) 2019 Mateusz Piotrowski <0mp@FreeBSD.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd August 24, 2019
.Dt MUCHUP 8
.Os
.Sh NAME
.Nm muchup
.Nd "perform source-based FreeBSD updates"
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl kipsw
.Sh DESCRIPTION
The primary objective of
.Nm
is to help with source-based updates of
.Fx
machines.
.Pp
.Nm
is using
.Xr filemon 4
to speed up builds.
See
.Xr build 7
for more details.
.Sh OPTIONS
.Bl -tag -width "-h"
.It Fl h
Print usage information.
.It Fl k
Run
.Dq make buildkernel .
.It Fl i
Run
.Xr beinstall 8 .
.It Fl p
Update the ports tree at
.Pa /usr/ports
to the latest revision.
.It Fl s
Update the src tree at
.Pa /usr/src
to the latest revision.
.It Fl w
Run
.Dq make buildworld .
.El
.Sh FILES
.Bl -tag -width "/var/log/muchup"
.It Pa /var/log/muchup
The location of logs generated by
.Nm .
.El
.Sh EXAMPLES
.Bl -tag -width 0n
.It Sy Example 1\&: No Updating the system with Nm
.Pp
The following command is going to update the src and the ports tree on the
machine, build, and install the results in a new boot environment.
.Bd -literal -offset 2n
.Li # Ic muchup -kipsw
.Ed
.El
.Sh SEE ALSO
.Xr build 7 ,
.Xr beinstall 8
.Sh AUTHORS
.Nm
was written by
.An Mateusz Piotrowski Aq Mt 0mp@FreeBSD.org .
