#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

# lib_require_root

FILES=
PREFIX="$HOME/.0mp-switchx/"
CUSTOMFILES='current-task profile'
CUSTOMOPTS="$(opts="${@%--}"; printf -- "${opts%% -- *}")"
lib_custom_install() {
    for file in $CUSTOMFILES
    do
        touch -- "$PREFIX""$file"
    done
}
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
