#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

# Standard module setup.
FILES='config'
PREFIX="$HOME/.subversion/"
lib_custom_install() { :; }
lib_back_up
trap lib_roll_back EXIT
lib_create_prefix_if_missing
lib_install
trap - EXIT

lib_info 'setup done'
