---
- name: Install tmux
  package: name=tmux state=present
  become: yes

- name: "Make #{pane_current_path} work when using tmux on a non-root account (see 229567)"
  become: yes
  sysctl:
    name: security.bsd.unprivileged_proc_debug
    value: "1"

- name: Symlink tmux configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ dotfiles_user_home }}/{{ item }}"
    state: link
    force: yes
  loop: "{{ configuration_files }}"
