#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

lib_require_root

while [ $# -gt 0 ] && [ "@$1@" != "@--@" ]
do
    case "$1" in
        --user) user="$2" ; shift 2 ;;
        *) lib_err "invalid argument \"$1\"" ; shift ;;
    esac
done

FILES=''
CUSTOMFILES='sysctl.conf'
PREFIX="/etc/"
lib_custom_install() {
    cp sysctl.conf "$PREFIX"sysctl.conf
    chown root:wheel "$PREFIX"sysctl.conf
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES=''
CUSTOMFILES='login_conf'
PREFIX="/home/$user/."
lib_custom_install() {
    cp login_conf "$PREFIX"login_conf
    chown "$user" "$PREFIX"login_conf
    cap_mkdb /etc/login.conf "$PREFIX"login_conf
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
