#! /bin/sh -
#
# Scripting helping to automate the FreeBSD CURRENT branch maintenance.

version=0.1.0

ncpu="$(sysctl -n hw.ncpu)"

CUSTOMOPTS="$(opts="${@%--}"; printf -- "${opts%% -- *}")"

set -e

# Get the latest source tree.
case "$CUSTOMOPTS" in
    *--update*)
        if ! pkg info -q subversion
        then
            pkg install -y subversion
        fi
        if ! [ -d /usr/src/.svn ]
        then
            rm -rf -- /usr/src/*
            svn co https://svn.freebsd.org/base/head /usr/src
        else
            svn update /usr/src
        fi
        if ! [ -d /usr/ports/.svn ]
        then
            rm -rf -- /usr/ports/*
            svn co https://svn.freebsd.org/ports /usr/ports
        else
            svn update /usr/ports
        fi
        ;;
esac

case "$CUSTOMOPTS" in
    *--build-kernel)
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildkernel
        ;;
    *--build-world)
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildworld
        ;;
    *--build*)
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildkernel
        make -j$ncpu buildworld
        ;;
    *--complete*)
        cd /usr/src
        make -j$ncpu installworld
        mergemaster -i -v -U
        ;;
esac

# Install the kernel.
case "$CUSTOMOPTS" in
    *--install-kernel*)
        cd /usr/src
        make -j$ncpu installkernel
        ;;
esac
