#! /bin/sh -
#
# Scripting helping to automate the FreeBSD CURRENT branch maintenance.

version=0.3.0

[ 0 -ne "$(id -u)" ] && echo 'error: roteste has to be run as root' && exit 1

ncpu="$(sysctl -n hw.ncpu)"

set -e

# Get the latest source tree.
case "$*" in
    *--update*)
        if ! [ -d /usr/src/.svn ]
        then
            rm -rf -- /usr/src/*
            svnlite co https://svn.freebsd.org/base/head /usr/src
        else
            svnlite update /usr/src
        fi
        if ! [ -d /usr/ports/.svn ]
        then
            rm -rf -- /usr/ports/*
            svnlite co https://svn.freebsd.org/ports/head /usr/ports
        else
            svnlite update /usr/ports
        fi
        ;;
esac

case "$*" in
    *--build-kernel)
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildkernel
        ;;
    *--build-world)
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildworld
        ;;
    *--build*)
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildkernel
        make -j$ncpu buildworld
        ;;
    *--complete*)
        cd /usr/src
        make -j$ncpu installworld
        mergemaster -i -v -U
        ;;
esac

# Install the kernel.
case "$*" in
    *--install-kernel*)
        cd /usr/src
        make -j$ncpu installkernel
        ;;
esac
