#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

FILES='fonts.conf'
PREFIX="$HOME/.config/fontconfig/"
mkdir -p "$PREFIX"
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES='justmount unitek-init wifi-init'
PREFIX="$HOME/bin/"
mkdir -p "$PREFIX"
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
