#! /bin/sh -
#
# Create a wlandev, start a WPA supplicant and run a dhclient.
#
# Version: 2.1.0
#
# Usage: $0 [wlandev [dev]]
#
# You can also pass `wlandev` and `dev` environmental variables to the
# script. The defaults are: "wlan0" and "iwm0" respectively.
#
# Send SIGQUIT with Control+\ to reinitiate the connection.

loopmode=no

case "$1" in
    -h|--help)

        cat <<EOF
Usage: ${0##*/} [-l] [wlandev [dev]]

Environmental variables:
    wlandev=wlan0
    dev=iwm0

Send SIGQUIT with Control+\ to reinitiate the connection.
EOF
        exit 0
        ;;
    -l|--loop)
        loopmode=yes
        shift
        ;;
    *)
        ;;
esac

reconnect() {
    set -x

    set -u

    if ! ifconfig "$wlandev" 1>&2 2>/dev/null
    then
        sudo ifconfig "$wlandev" create wlandev "$dev"
    else
        sudo service netif restart "$wlandev"
    fi

    sudo ifconfig "$wlandev" up
    sudo wpa_supplicant -B -i "$wlandev" -c /etc/wpa_supplicant.conf
    if sudo dhclient "$wlandev"
    then
        { set +x; } 2>/dev/null
        return 0
    else
        { set +x; } 2>/dev/null
        return 1
    fi
}

keep_reconnecting() {
    while ! reconnect
    do done
}

wlandev="${wlandev:-${1:-wlan0}}"
dev="${dev:-${2:-iwm0}}"

trap 'keep_reconnecting' SIGQUIT # It's Ctrl-\.

if [ "@$loopmode@" = "@no@" ]
then
    keep_reconnecting
else
    while keep_reconnecting
    do
        while ifconfig "$wlandev" | grep 'status: associated' >/dev/null 2>&1
        do
            sleep 5
        done
    done
fi
