#! /bin/sh -
#
# Fit your QEMU console running in a tmux session.
#
# The idea is to focus on a pane running QEMU and adjust its stty size.  It is
# achived by prompting tmux for information about the current pane size and
# sending a command adjusting the stty size in QEMU accordingly.
#
# Usage:
# 1. Switch to the pane running QEMU.
# 2. Make sure that you're in a shell (and not Vim or less) as you will be
#    sending keystrokes directly into the shell running inside the pane in a
#    while.
# 3. Hit your tmux prefix and call ':run fitqemu' (assuming that fitqemu is
#    present in your current path).

# version=0.1.1

get_info() {
    format='#{pane_active} #{pane_index} #{pane_height} #{pane_width}'
    tmux list-panes -F "$format" | awk '{ if ($1 == 1) { print $2, $3, $4 } }'
}

info="$(get_info)"

index="$(printf '%s' "$info" | awk '{print $1}')"
height="$(printf '%s' "$info" | awk '{print $2}')"
width="$(printf '%s' "$info" | awk '{print $3}')"

tmux send-keys -t "$index" "stty rows $height cols $width"

