#! /bin/sh -
#
# Copyright (c) 2017-2018 Mateusz Piotrowski <0mp@FreeBSD.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

usage() {
	printf -- '%s\n' "Usage: previewman [-h] manpage [pattern] [match-number]"
	printf -- '%s\n' "Version: ${version}"
}

version='0.1.2'

manpager='timeout 0.1s less --no-init --quit-on-intr'

while [ $# -gt 0 ]
do
	case $1 in
	( -h | --help )
		shift
		usage
		exit 0
		;;
	--)
		shift
		break
		;;
	*)
		break
		;;
	esac
done

if [ $# -lt 1 ]
then
	usage
	exit 1
fi

filename="${1}"
shift

if [ $# -ge 1 ]
then
	manpager="${manpager} --pattern $(printf -- %s "${1}" | sed -E 's|\([[:space:]]\)|\\\\1|g')"
	shift
fi

if [ $# -ge 1 ]
then
	manpager="${manpager} +${1}n"
	shift
fi

printf '%s\n' "${filename}" | \
    entr -c env MANPAGER="${manpager}" sh -c "man \"./${filename}\" " 2>/dev/null
