#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

FILES="$(cat <<-EOF
0mp-explore
cflowfilter
committer-bootstrap
disable-yoga-3-14-touchscreen
faf
flip-git-remote-url
get-list-of-ports-for-moinmoin
manlint
previewman
radio
resizetty
samsung2043nw
superdrive
test-true-color-support
EOF
)"
PREFIX="$HOME/.local/bin/"
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES="$(cat <<-EOF
0mp-explore.1
EOF
)"
PREFIX="$HOME/.local/share/man/man1/"
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info remember to add ~/.local/bin to your PATH

lib_info 'setup done'
