#! /bin/sh -

. ../lib.sh

set -eu

FILES="0mp-explore fitqemu moinmoincli cflowfilter superdrive"

BIN_DIR=~/bin

lib_info setup

mkdir -p "$BIN_DIR"
PREFIX="$BIN_DIR/"
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info remember to add ~/bin to your PATH
lib_info 'setup done'
