#! /bin/sh -

. ../lib.sh

set -eu

FILES="$(cat <<-EOF
0mp-explore
cflowfilter
disable-yoga-3-14-touchscreen
faf
fitqemu
moinmoincli
superdrive
EOF
)"

BIN_DIR=~/bin

lib_info setup

mkdir -p "$BIN_DIR"
PREFIX="$BIN_DIR/"
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info remember to add ~/bin to your PATH
lib_info 'setup done'
