#! /bin/sh -
#
# Version: 0.3.0

file="$HOME/.suckless/current-task.txt"

if [ -z "$*" ]; then
    echo "Usage: current-task -c|-|-<number>|<text>"
    exit 0
fi

case "$1" in
    -c)
        printf '' > "$file"
        ;;
    -)
        sed -i '' -e '$ d' "$file"
        ;;
    -[1-9])
        awk -v ln="${1#-}" 'NR != ln{print $0}' "$file" > "$file.tmp"
        mv "$file.tmp" "$file"
        ;;
    --|*)
        [ "$1" = "--" ] && shift
        cat >> "$file" <<EOF
[$(date +%H:%M)] $*
EOF
        ;;
esac
