#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

CUSTOMOPTS="$(opts="${*%--}"; printf -- '%s' "${opts%% -- *}")"

PREFIX="$HOME/.0mp-switch/"
lib_create_prefix_if_missing

FILES='battery-alert.sh eyes-alert.sh freebsd-logo-by-claudiom.png plumb.sh status-bar.sh'
PREFIX="$HOME/.suckless/"
lib_custom_install() {
    case $CUSTOMOPTS in
        *--wallpaper*)
            feh -B white --bg-tile ~/.suckless/freebsd-logo-by-claudiom.png
            ;;
    esac
}
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES='xinitrc'
PREFIX=
lib_custom_install() { :; }
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES='current-task'
PREFIX="$HOME/.local/bin/"
lib_custom_install() { :; }
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
