#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

CUSTOMOPTS="$(opts="${@%--}"; printf -- "${opts%% -- *}")"
case "$CUSTOMOPTS" in
    *--root-install*)
        lib_require_root
        if pkg lock --show-locked 2>/dev/null | grep dwm 1>/dev/null
        then
            pkg unlock -y dwm
        fi
        export DWM_CONF="$PWD/config.h"
        cd /usr/ports/x11-wm/dwm
        make deinstall
        make clean
        make reinstall
        pkg lock -y dwm
        ;;
    *)
        FILES='status-bar.sh'
        PREFIX="$HOME/.suckless/"
        lib_back_up
        trap lib_roll_back EXIT
        lib_install
        trap - EXIT

        FILES='xinitrc'
        PREFIX=
        lib_back_up
        trap lib_roll_back EXIT
        lib_install
        trap - EXIT
        ;;
esac

lib_info 'setup done'
