#! /bin/sh -

while [ -d ~/.suckless ] && [ -f ~/.suckless/status-bar.sh ]
do
    /bin/sh ~/.suckless/status-bar.sh &
    /bin/sh ~/.suckless/low-battery-alert.sh &
    sleep 4
done &

setxkbmap pl

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

# Wallpaper.
if [ -f ~/.fehbg ]
then
    sh ~/.fehbg
else
    feh -B white --bg-tile ~/.suckless/fehbg.freebsd-128.png
fi

which intel_backlight 1>/dev/null 2>&1 && intel_backlight 30

exec dwm
