#! /bin/sh -

while [ -d ~/.suckless ] && [ -f ~/.suckless/status-bar.sh ]
do
    /bin/sh ~/.suckless/status-bar.sh
    sleep 10
done &

setxkbmap pl

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

xsetroot -solid yellow

exec dwm
