#! /bin/sh -

while [ -d ~/.suckless ] && [ -f ~/.suckless/status-bar.sh ]
do
    /bin/sh ~/.suckless/status-bar.sh
    sleep 10
done &

setxkbmap pl

[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap

xsetroot -solid yellow

which intel_backlight 1>/dev/null 2>&1 && intel_backlight 30

exec dwm
