#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

# Make sure that Firefox is installed.
if ! which firefox
then
    lib_err 'Firefox is not installed'
    exit 1
fi

# Make sure that Firefox has already created a profile directory.
profiledir="$(find ~/.mozilla/firefox/ -maxdepth 1 -mindepth 1 -name '*.default' -type d)"
if ! [ -d "$profiledir" ]
then
    lib_err 'Unable to detect Firefox profile directory'
    exit 1
fi

FILES='user.js'
PREFIX="$profiledir/"
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
