#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

lib_require_root

while [ $# -gt 0 ] && [ "@$1@" != "@--@" ]
do
    case "$1" in
        --user) user="$2" ; shift 2 ;;
        *) lib_err "invalid argument \"$1\"" ; shift ;;
    esac
done

FILES='plumb.sh'
PREFIX="/home/$user/.suckless/"
su "$user" -c "mkdir -p $PREFIX"
lib_custom_install() {
    cd sterm-0mp
    for flavor in shine charcoal data
    do
        if pkg info -e sterm-0mp-$flavor
        then
            make deinstall FLAVOR=$flavor
        fi
        make clean FLAVOR=$flavor
        make BATCH=YES FLAVOR=$flavor
        make install FLAVOR=$flavor
    done

    ln -s -f /usr/local/bin/st-charcoal /usr/local/bin/st
    ln -s -f /usr/local/bin/st-shine /usr/local/bin/st2
    chown -h "$user:$user" "$PREFIX"plumb.sh
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
