#! /bin/sh -

set -eu

cd -- "${0%/*}"
rm -f -- sterm/files/*

cd sterm
make clean >/dev/null
make extract >/dev/null

cd work/st-*
for f in *
do
    cp "$f" "$f".vanilla
done
cd ../..

for p in $PWD/../patches/*
do
    cd work/st-*
    patch -p1 < "$p"
    for f in *
    do
        case "$f" in
            *vanilla|*orig) continue ;;
            *) cp "$f".vanilla "$f".orig ;;
        esac
    done
    cd ../..
done
make makepatch
make clean
