---
- name: Install Vim and its runtime dependencies
  package:
    name:
      - vim
    state: present
  become: yes

- name: Install runtime dependencies of my Vim configuration
  package:
    name:
      - curl
      - markdownfmt
      - py36-black
    state: present
  become: yes
