#! /bin/sh -

. ../lib.sh

set -eu

MODULE_NAME=tmux
FILES='tmux.conf'

lib_info 'setup'

if [ "x$(uname)" = xDarwin ]
then
    FILES="$FILES tmux-macos.conf"
elif [ "x$(uname)" = xLinux ]
then
    FILES="$FILES tmux-linux.conf"
fi

lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
