#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

FILES='tmux.conf tmux-shine.conf tmux-charcoal.conf'
case "$(uname)" in
    Darwin)
        FILES="$FILES tmux-macos.conf"
        ;;
    FreeBSD)
        FILES="$FILES tmux-freebsd.conf"
        ;;
    Linux)
        FILES="$FILES tmux-23.conf tmux-24+.conf"
        ;;
    *)
        ;;
esac
PREFIX=
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES=
PREFIX="$HOME/.0mp-switch/"
CUSTOMFILES='profile'
lib_custom_install() {
    for file in $CUSTOMFILES
    do
        touch -- "${PREFIX}${file}"
    done
}
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES=
PREFIX=
CUSTOMFILES=
CUSTOMOPTS="$(opts="${*%--}"; printf -- '%s' "${opts%% -- *}")"
lib_custom_install() {
    case $CUSTOMOPTS in
        *--freebsd*)
            lib_run_as_root $CUSTOMOPTS
            ;;
    esac
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT


lib_info 'setup done'
