#! /bin/sh -
#
# Ubuntu:
# http://rhunter.org/blog/2012/04/17/dwm-a-tutorial-for-beginners/
# https://cannibalcandy.wordpress.com/2012/04/26/installing-and-configuring-dwm-under-ubuntu/

. ../lib

set -eu

MODULE_NAME=dwm
FILES=""

lib_info setup

if uname -a | grep Ubuntu 1> /dev/null
then
    sudo apt-get update
    sudo apt-get -y install build-essential libx11-dev libxinerama-dev \
        libxft-dev suckless-tools
    sudo apt-get -y install dwm
    cd dwm
    make
    sudo make clean install
    cd ..

    lib_back_up
    trap lib_roll_back EXIT
    lib_install
    trap - EXIT
else
    lib_err 'no installation instructions are specified for this platform; skipping'
    exit 0
fi

lib_info 'setup done'
