---
- name: Disable console beep
  become: yes
  sysctl:
    name: kern.vt.enable_bell
    value: "0"

- name: Update microcode
  become: yes
  block:
    - name: Install devcpu-date
      package:
        name: devcpu-data
        state: latest
    - name: Enable updating microcode
      sysrc:
        name: microcode_update_enable
        value: "YES"

- name: Install login_conf
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ dotfiles_user_home }}/{{ item }}"
    state: hard
    force: yes
  loop: [ .login_conf ]
