#! /bin/sh -
#
# Version: 0.1.0

set -u

user="${1}"
email="${2}"

curl -v -d "nickname=${user}" -d "email=${email}" -d "description=FreeBSD/$(uname -m) on $(kenv smbios.system.maker) $(kenv smbios.system.product)" -d "do=addd" --data-urlencode 'dmesg@/var/run/dmesg.boot' http://dmesgd.nycbug.org/index.cgi
