#! /bin/sh -
#
# Version: 0.2.0

set -u

if [ $# -lt 2 ]
then
    cat <<EOF >&2
Usage: ${0##*/} user email
EOF
    exit 1
fi

user="${1}"
email="${2}"

curl -v -d "nickname=${user}" -d "email=${email}" -d "description=FreeBSD/$(uname -m) on $(kenv smbios.system.maker) $(kenv smbios.system.product)" -d "do=addd" --data-urlencode 'dmesg@/var/run/dmesg.boot' http://dmesgd.nycbug.org/index.cgi
echo ''
