#! /bin/sh -
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2018 Mateusz Piotrowski <0mp@FreeBSD.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     1. Redistributions of source code must retain the above copyright notice,
#        this list of conditions and the following disclaimer.
#     2. Redistributions in binary form must reproduce the above copyright
#        notice, this list of conditions and the following disclaimer in the
#        documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# ---
# Scripting helping to automate the FreeBSD CURRENT branch maintenance.

# I've found out that the PORTS_MODULES mechanism does not work well if it is
# not cleaned before running `buildkernel`. The port does not get rebuiled
# resulting in an installation of a port too old for the newly built kernel.
clean_ports_modules() {
    for conf in /etc/src.conf /etc/make.conf
    do
        for module in $(sysrc -q -f "$conf" PORTS_MODULES)
        do
            cd "/usr/src/$module" && make clean
        done
    done
}

version=1.3.0

if [ $# -eq 0 ]
then
    cat <<__end_of_usage
Usage: roteste [-ekipsw | -c [-b]]
Version: $version
__end_of_usage
elif [ 0 -ne "$(id -u)" ]
then
    echo 'error: roteste has to be run as root' && exit 1
fi

ncpu="$(sysctl -n hw.ncpu)"

set -e

args=`getopt bcekipsw $*`
set -- $args

while :; do
    case "$1" in
        -b)
            bectl=yes
            shift
            ;;
        -c)
            complete=yes
            shift
            ;;
        -e)
            etcupdate=yes
            shift
            ;;
        -k)
            kernel=yes
            shift
            ;;
        -i)
            install=yes
            shift
            ;;
        -p)
            ports=yes
            shift
            ;;
        -s)
            src=yes
            shift
            ;;
        -w)
            world=yes
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [ "$etcupdate" ]
then
    etcupdate extract
fi

# Get the latest source tree.
if [ "$src" ]
then
    if ! [ -d /usr/src/.svn ]
    then
        rm -rf -- /usr/src/*
        svnlite co https://svn.freebsd.org/base/head /usr/src
    else
        svnlite update /usr/src
    fi
fi

if [ "$ports" ]
then
    if ! [ -d /usr/ports/.svn ]
    then
        rm -rf -- /usr/ports/*
        svnlite co https://svn.freebsd.org/ports/head /usr/ports
    else
        svnlite update /usr/ports
    fi
fi

if [ "$complete" ]
then
    cd /usr/src
    if [ "$bectl" ]
    then
        bectl create "$(uname -v | awk -v OFS=_ '{$1 = $1; print}')_$(date +%Y-%m-%d_%Hh%Mm%Ss)"
    fi
    make -j$ncpu installworld
    etcupdate diff
    etcupdate
    etcupdate resolve
else
    if [ "$world" ]
    then
        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildworld
    fi

    if [ "$kernel" ]
    then
        clean_ports_modules

        cd /usr/src
        kldstat -q -n filemon || kldload filemon
        make -j$ncpu buildkernel
    fi

    # Install the kernel.
    if [ "$install" ]
    then
        cd /usr/src
        make -j$ncpu installkernel
    fi
fi
