#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

FILES='flip-svn-location fr justmount nycbug-dmesgd muchup ports unitek-init wifi-init'
PREFIX="$HOME/.local/bin/"
lib_custom_install() { :; }
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES="$(cat <<-EOF
rotezukunft.8
EOF
)"
PREFIX="$HOME/.local/share/man/man8/"
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
