#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

FILES=
PREFIX=
CUSTOMFILES='login_conf'
lib_custom_install() {
    for f in $CUSTOMFILES
    do
        ln -v -f -F -n -- "$f" "$PREFIX$f"
    done
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

FILES='flip-svn-location fr justmount nycbug-dmesgd rotezukunft rotezukunft.8 unitek-init wifi-init'
PREFIX="$HOME/.local/bin/"
lib_custom_install() { :; }
lib_create_prefix_if_missing
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
