#! /bin/sh -
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2018 Mateusz Piotrowski <0mp@FreeBSD.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     1. Redistributions of source code must retain the above copyright notice,
#        this list of conditions and the following disclaimer.
#     2. Redistributions in binary form must reproduce the above copyright
#        notice, this list of conditions and the following disclaimer in the
#        documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# ---
# Create a wlandev, start a WPA supplicant and run a dhclient.
# ---
# Version: 2.7

loopmode=no

case "$1" in
    -h|--help)

        cat <<EOF
Usage: ${0##*/} [-l] [wlandev [dev]]

Environmental variables:
    wlandev=wlan0
    dev=iwm0

Send SIGQUIT with Control+\ to reinitiate the connection.
EOF
        exit 0
        ;;
    -l|--loop)
        loopmode=yes
        shift
        ;;
    *)
        ;;
esac

wlandev="${wlandev:-${1:-wlan0}}"
dev="${dev:-${2:-iwm0}}"

sudo sh -c "$(cat <<EOF

reconnect() {
    set -x

    set -u

    if ! ifconfig "$wlandev" >/dev/null 2>&1
    then
        ifconfig "$wlandev" create wlandev "$dev" >/dev/null || return 1
    else
        service netif restart "$wlandev" || return 1
    fi

    ifconfig "$wlandev" up
    wpa_supplicant -B -i "$wlandev" -c /etc/wpa_supplicant.conf
    killall dhclient
    if dhclient "$wlandev"
    then
        { set +x; } 2>/dev/null
        return 0
    else
        { set +x; } 2>/dev/null
        return 1
    fi
}

keep_reconnecting() {
    reconnect
    sleep 1
    while :
    do
        if ifconfig "$wlandev" | grep 'status: associated' >/dev/null 2>&1
        then
            [ "@$loopmode@" = "@no@" ] && break
            sleep 5
        else
            reconnect
        fi
    done
}

# Set the maximal core dump file size to 0 so that they are not created at all.
ulimit -c 0
trap 'keep_reconnecting' SIGQUIT # It's Ctrl-\.

keep_reconnecting

EOF
)"
