#! /bin/sh -

. ../lib.sh

set -eu

FILES='bash_0mp inputrc'

lib_info 'setup'

# Standard module setup.
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

# Make bashrc source bash_0mp.
lib_install() {
    sourcecmd='[ -f ~/.bash_0mp ] && . ~/.bash_0mp'
    if ! grep "$sourcecmd" ~/.bashrc 2>/dev/null 1>&2
    then
        printf '\n%s\n' "$sourcecmd" >> ~/.bashrc
    fi
    lib_install_file "$PWD/inputrc" "$HOME/.inputrc"
}
FILES='bashrc'
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
