#! /bin/sh -

. ../lib.sh

set -eu

lib_info 'setup'

# Standard module setup.
FILES='bash_0mp inputrc bash_profile'
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

# Make bashrc source bash_0mp.
FILES=''
CUSTOMFILES='bashrc'
lib_custom_install() {
    sourcecmd='[ -r ~/.bash_0mp ] && . ~/.bash_0mp'
    if ! grep "$sourcecmd" ~/.bashrc 2>/dev/null 1>&2
    then
        printf '\n%s\n' "$sourcecmd" >> ~/.bashrc
    fi
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
