#! /bin/sh -
#
# NB: In Vim, execute selection with ":terminal sh".

clean_up() {
    if [ "$SSH_AGENT_PID" ]; then
        kill "$SSH_AGENT_PID"
    fi

    ~/.local/etc/rc.d/sxhkd stop
    ~/.local/etc/rc.d/status-bar stop
    ~/.local/etc/rc.d/battery-alert stop
    ~/.local/etc/rc.d/eyes-alert stop
    ~/.local/etc/rc.d/pie-menu stop
    ~/.local/etc/rc.d/inputplug stop
    ~/.local/etc/rc.d/sctd stop
}

trap 'clean_up' EXIT

export LANG=en_US.UTF-8
export LC_TIME=en_GB.UTF-8

mkdir -p ~/.cache
~/.local/etc/rc.d/status-bar start
~/.local/etc/rc.d/battery-alert start
~/.local/etc/rc.d/eyes-alert start
~/.local/etc/rc.d/pie-menu start
~/.local/etc/rc.d/inputplug start
~/.local/etc/rc.d/sctd start
# Some of the shortcuts are broken if sxhkd starts too early.
sleep 5 && ~/.local/etc/rc.d/sxhkd start &

[ -f ~/.xmodmap ] && xmodmap ~/.xmodmap

feh --no-fehbg --bg-center --image-bg 'black' "${HOME}/.config/desktop/freebsd-logo-by-claudiom.png"

eval $(ssh-agent -s)
gpg-connect-agent reloadagent /bye

$(which dbus-run-session) sh -c '
	"$@"
	while [ -f ~/.cache/restart-dwm ]; do
		"$@" || break
	done
' xinitsh "${@:-dwm}"
