#! /bin/sh -
#
# Version 1.1

require() {
	if ! command -v "$1" >/dev/null; then
		printf "%s\n" "ERROR: Command not found: $1" >&2
		exit 1
	fi
}

require notify-send

pause="$((60 * 15))"

while :; do
    sleep "$pause"
    [ -f ~/.cache/eyes-alert-off ] && continue
    notify-send --urgency=low "#.#"
done
