#! /bin/sh -
#
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2018-2021 Mateusz Piotrowski <0mp@FreeBSD.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     1. Redistributions of source code must retain the above copyright notice,
#        this list of conditions and the following disclaimer.
#     2. Redistributions in binary form must reproduce the above copyright
#        notice, this list of conditions and the following disclaimer in the
#        documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

## Functions

as_user() {
    sudo --login --user "$SUDO_USER" -- "$@"
}

as_root() {
    sudo --login --user "root" -- "$@"
}

die() {
    printf 'FATAL: %s\n' "$*" >&2
    exit 1
}

usage() {
    cat << USAGE
Usage: sudo $progname [-hikpsw]

Version: $version

Options:
-h  Show usage message.
-i  Install the system with beinstall(8).
-k  Run buildkernel.
-p  Update the ports tree.
-s  Update the src tree.
-w  Run buildworld.

Environment:
SUDO_USER  Unprivlieged user who owns trees and runs build jobs.
USAGE
}

require() {
	if ! command -v "$1" >/dev/null; then
		die "Command not found: $1"
	fi
}

update_git() {
    local _dir="$1"
    local _url="$2"
    shift 2

    as_user mkdir -p -- "$base_dir"

    if [ -d "$_dir" ]; then
        as_user git -C "$_dir" pull --autostash
    else
        as_user git clone "$@" "$_url" "$_dir"
    fi
}

update_src() {
    update_git "$src_dir" https://git.freebsd.org/src.git \
        --config remote.freebsd.fetch='+refs/notes/*:refs/notes/*'
}

update_ports() {
    update_git "$ports_dir" https://github.com/freebsd/freebsd-ports
}

parse_args() {
    # Print usage and quit if no arguments were provided.
    if [ $# = 0 ]; then
        usage
        exit 0
    fi

    # Try to extract the unprivliged username from SUDO_USER.
    user="$SUDO_USER"
    # The directory to store source trees.
    base_dir="/usr/home/$user/.local/share/freebsd"
    # The directory to store the FreeBSD src tree.
    src_dir="$base_dir/src"
    # The directory to store the FreeBSD ports tree.
    ports_dir="$base_dir/ports"

    # Parse command-line arguments.
    OPTIND=1
    while getopts hkipsw _opt; do
        case "$_opt" in
            h) usage; exit 0 ;;
            i) flag_i="yes" ;;
            k) flag_k="yes" ;;
            p) flag_p="yes" ;;
            s) flag_s="yes" ;;
            w) flag_w="yes" ;;
            ?)
                die "Unknown option: $_opt"
                ;;
        esac
    done
    if [ "$OPTIND" -ne 0 ]; then
        shift "$(( OPTIND - 1 ))"
    fi

    # Require that variable "user" is set.
    if [ -z "$user" ]; then
        die "User not set"
    fi

    # Make sure that the value of user makes sense.
    if [ "$user" = "root" ]; then
        die "User must not be set to root"
    fi
    if ! id "$user" >/dev/null 2>&1; then
        die "User does not exist: $user"
    fi
}

build_base_component() {
    as_user make -C "$src_dir" -j "$(sysctl -n hw.ncpu)" PORTSDIR="$ports_dir" "$1"
}

build_world() {
    build_base_component buildworld
}

build_kernel() {
    build_base_component buildkernel
}

run_beinstall() {
    as_root sh -c "$(cat << BEINSTALL
cd "$src_dir" && \
env NO_PKG_UPGRADE=YES ./tools/build/beinstall.sh -j "$(sysctl -n hw.ncpu)" PORTSDIR="$ports_dir"
BEINSTALL
    )"
}

main() {
    # Make sure that all the necessary programs are available.
    require git

    # Parse the command-line arguments.
    parse_args "$@"

    # Run the actual commands to update the system.
    if [ "$flag_w" = "yes" ] || [ "$flag_k" = "yes" ]; then
        as_root kldload -n filemon
    fi
    if [ "$flag_s" = "yes" ]; then
        update_src
    fi
    if [ "$flag_p" = "yes" ]; then
        update_ports
    fi
    if [ "$flag_w" = "yes" ]; then
        build_world
    fi
    if [ "$flag_k" = "yes" ]; then
        build_kernel
    fi
    if [ "$flag_i" = "yes" ]; then
        run_beinstall
    fi
}

## Globals & constants

progname="${0##*/}"
version="4.0.0"

flag_i="no"
flag_k="no"
flag_p="no"
flag_s="no"
flag_w="no"

## Body

set -eu

main "$@"

exit 0

# vim: filetype=sh softtabstop=4 shiftwidth=4 tabstop=4 expandtab
