#! /bin/sh -

require() {
	if ! command -v "$1" >/dev/null; then
		printf "%s\n" "ERROR: Dependency not found: $1" >&2
		exit 1
	fi
}

loop() {
	items="
IMG:/usr/local/share/pixmaps/firefox.png	firefox
IMG:/usr/local/share/pixmaps/thunderbird.png	thunderbird
IMG:/home/0mp/Downloads/lock.png			slock
"
	printf '%s\t%s\n' $items | pmenu | sh >/dev/null 3>&1
}

require pmenu
require xclickroot

if [ "$1" = "loop" ]; then
	loop
else
	exec xclickroot -r "${0}" loop
fi
