#! /bin/sh -

require() {
	if ! command -v "$1" >/dev/null; then
		printf "%s\n" "ERROR: Dependency not found: $1" >&2
		exit 1
	fi
}

set -eu

require pmenu

pidfile="$1"

(pmenu -r 3 <<ITEMS & echo $! > "$pidfile"; wait) | sh >/dev/null 2>&1
IMG:/usr/local/share/pixmaps/firefox.png	firefox
IMG:/usr/local/share/pixmaps/thunderbird.png	thunderbird
IMG:/home/0mp/Downloads/lock.png		slock
ITEMS
