#! /bin/sh -

reload() {
	exec "$0"
}

trap reload SIGUSR1

batteries() {
	local _num_of_batteries
	local _battery

	if [ -f ~/.cache/battery-alert-off ]; then
		printf -- '! '
	fi

	_num_of_batteries="$(sysctl -n hw.acpi.battery.units)"

	if [ -z "${_num_of_batteries}" ]
	then
		return 0
	fi

	for _battery in $( seq 0 "$(( _num_of_batteries - 1 ))" )
	do
		if ! acpiconf -i "$_battery" | awk '
			BEGIN {
				recognized = 0
			}
			/Remaining capacity*/ {
				printf "%s", $3
				recognized = 1
			}
			/State:[[:space:]]+charging/ {
				printf "+"
				recognized = 1
			}
			/Remaining time:[[:space:]]+.*:.*/ {
				printf " (%s)", $3
				recognized = 1
			}
			END {
				exit recognized == 0
			}
			'
		then
			printf '%s' '?%'
		fi
		printf %s ' | '
	done
}

network_interface() {
	local _if
	local _ssid
	local _ip
	_if="$1"
	_ip="$(ifconfig "$_if" | awk '/\tinet /{print $2}')"
	_ssid="$(ifconfig "$_if" | awk '/\tssid /{print $2}')"
	printf -- '%s%s%s' "${_ssid:-}" "${_ssid:+ }" "${_ip:-}"
	printf -- ' | '
}

status_bar() {
	printf ' '

	# Mixer
	if mixer -S pcm | grep -q '0:0'; then
		printf '%s' 'M '
	fi
	mixer -s vol | cut -d " " -f 2
	printf ' | '

	# Eyes alert
	[ -f ~/.cache/eyes-alert-off ] && printf -- '!'
	sysctl -n hw.acpi.video.lcd0.brightness
	if [ -e ~/.cache/sctd.log ]; then
		printf ' '
		awk 'END {print $NF}' ~/.cache/sctd.log
	fi
	printf ' | '

	# Battery
	batteries

	# Networking
	if ! drill >/dev/null 2>&1
	then
		printf -- '! '
	fi
	network_interface wlan0

	# Date
	date +'%A, %Y-%m-%d (%B) %H:%M '
}

while xsetroot -name "$(status_bar | tr -d '\n')"
do
    sleep 2
done
