#! /bin/sh -
#
# https://wiki.freebsd.org/Laptops/Lenovo_Yoga_3_14

. ../lib.sh

set -eu

lib_info 'setup'

lib_require_root

set_once() {
    filename="$1"
    string="$2"
    if ! grep "$string" "$filename" >/dev/null 2>&1
    then
        printf '%s\n' "$string" >> "$filename"
    fi
}

FILES=
PREFIX=
CUSTOMFILES=
lib_custom_install() {
    # Fix the headphones jack.
    set_once '/boot/device.hints' 'hint.hdaa.1.nid22.config="as=1 seq=15"'

    # Disable the power button (https://forums.freebsd.org/threads/56807/).
    set_once '/etc/sysctl.conf' 'hw.acpi.power_button_state=NONE'

    # Disable the console bell.
    set_once '/etc/sysctl.conf' 'kern.vt.enable_bell=0'

    # Load acpi_video for backlight support.
    sysrc kld_list+=acpi_video

    # Enable moused with some empirically tested flags.
    sysrc moused_enable="YES" moused_flags="-A 1.65 -a 1.1"
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
