#! /bin/sh -
#
# https://wiki.freebsd.org/Laptops/Lenovo_Yoga_3_14

. ../lib.sh

set -eu

lib_info 'setup'

lib_require_root

set_once() {
    filename="$1"
    string="$2"
    if ! grep "$string" "$filename" >/dev/null 2>&1
    then
        printf '%s\n' "$string" >> "$filename"
    fi
}

FILES=
PREFIX=
CUSTOMFILES=
CUSTOMOPTS="$(opts="${@%--}"; printf -- "${opts%% -- *}")"
lib_custom_install() {
    case "$CUSTOMOPTS" in ?*)
        pkg update
    esac

    # Fix the headphones jack.
    set_once '/boot/loader.conf' 'hint.hdaa.1.nid22.config="as=1 seq=15"'

    # Disable the power button (https://forums.freebsd.org/threads/56807/).
    set_once '/etc/sysctl.conf' 'hw.acpi.power_button_state=NONE'

    # Lower the screen brightness to a reasonable level.
    set_once '/etc/sysctl.conf' 'hw.acpi.video.lcd0.brightness=6'

    # Disable the console bell.
    set_once '/etc/sysctl.conf' 'kern.vt.enable_bell=0'

    # Enable D-BUS.
    sysrc dbus_enable="YES"

    # Load acpi_video for backlight support.
    sysrc kld_list+=acpi_video

    # Configure Intel drivers.
    # For some reason, i915kms has to be loaded using its absolute path.
    # It is not recommended to install x11-drivers/xf86-video-intel alongside
    # graphics/drm-next-kmod.
    case "$CUSTOMOPTS" in
        *--intel*) pkg install -y graphics/drm-next-kmod
    esac
    sysrc kld_list+="/boot/modules/i915kms.ko"

    # Enable moused with some empirically tested flags.
    sysrc moused_enable="YES" moused_flags="-A 1.65 -a 1.1"

    # Configure the iwm wireless network device.
    # Actually, it might be better to move if_iwm and iwm3160fw to
    # /boot/loader.conf at some point.
    sysrc kld_list+='if_iwm iwm3160fw'
    sysrc wlans_iwm0='wlan0' ifconfig_wlan0='WPA DHCP'

    # Configure powerdxx (and disable powerd).
    case "$CUSTOMOPTS" in
        *--powerdxx*) pkg install -y sysutils/powerdxx
    esac
    sysrc powerd_enable=NO
    sysrc powerdxx_enable=YES
    sysrc powerdxx_flags="--ac hiadaptive --batt minimum --unknown hiadaptive"
    sysrc performance_cx_lowest="Cmax"
    sysrc economy_cx_lowest="Cmax"

    # Install missing fonts.
    case "$CUSTOMOPTS" in
        *--fonts*) pkg install -y x11-fonts/noto
    esac
}
lib_back_up
trap lib_roll_back EXIT
lib_install
trap - EXIT

lib_info 'setup done'
